### ISSUE TITLE
Upgrade plyr and add download button to video player

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework-files#111]
This question comes up often. People want video and download. Plyr offers a download button, see: https://codepen.io/anon/pen/gZYEme 

For FILEman: the download button should always show
For DOCman; the download button should show if the user has download permissions (*)

(*) We might need to check that the video plyr always works, even if the user only has view permissions, this allows us to offer view vs download of videos.

**Comment by jebbdomingo** [comment]
#### DOCman document
![image](https://user-images.githubusercontent.com/5572579/84646211-52c4a280-af34-11ea-9b3b-ea359eba6168.png)
