### ISSUE TITLE
Supporting Mimetypes

### ISSUE THREAD

**Issue by rmdstudio** [joomlatools/joomlatools-framework-files#14]
Components that extend this framework may need a mimetype => extension map. Implement models, entities, and behaviours needed for the child classes to access this mimetype map.

Note: this feature will be used in DOCman

**Comment by rmdstudio** [comment]
@ercanozkaya @johanjanssens I need to push a branch to this repository, but I don't think I have the right permissions.

**Comment by rmdstudio** [comment]
@ercanozkaya I forked to my account and did a PR

**Comment by ercanozkaya** [comment]
Thanks @rmdstudio I'll take a look at the permission issue.
