### ISSUE TITLE
Uploader drag and drop flickering 

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework-files#33]
There's a known issue with Dropzone on Chrome and IE on which the drop file area constantly flickers and it's behavior is rather erratic.

See:

- https://support.joomlatools.com/forums/topic/7424-dragging-files-to-upload-not-working-properly
- https://support.joomlatools.com/forums/topic/7499-problem-with-drag-and-drop-in-firefox-53-0
- https://support.joomlatools.com/forums/topic/7547-problem-with-drag-and-drop-in-firefox-53-0
- https://support.joomlatools.com/tickets/topic/8041
- https://support.joomlatools.com/tickets/topic/8184

References:

- https://github.com/enyo/dropzone/issues/438

**Comment by amazeika** [comment]
@ercanozkaya Please review and test this. Seems to work ok on chrome, IE and FF.

**Comment by ercanozkaya** [comment]
@amazeika Nice fix 👍 Merged into master and 3.1

**Comment by amazeika** [comment]
Moved ticket to open again since it seems that there are still problems under FF on Windows.

See:

- https://support.joomlatools.com/forums/topic/7547

**Comment by amazeika** [comment]
Personal note: I could be helpful to update plupload, we are running a rather old version of it.

**Comment by amazeika** [comment]
Personal note: Upgrading plupload to its latest version didn't help on resolving this issue. Further investigation is needed on this one.

**Comment by ercanozkaya** [comment]
Client confirmed the fix, @amazeika could you please do a quick check too before I merge this?
