### ISSUE TITLE
Add isAudio and isVideo methods to the file entity

### ISSUE THREAD

**Issue by rmdstudio** [joomlatools/joomlatools-framework-files#36]
We need two methods isAudio and isVideo in the file entity which can be used for knowing where to render a player. Also update the player helper to use these methods.

**Comment by rmdstudio** [comment]
@ercanozkaya @johanjanssens the list of supported files are now duplicated in entity and player parent class. What's the best strategy to DRY the code?

https://github.com/joomlatools/joomlatools-framework-files/blob/feature/36-is-audio-video/model/entity/file.php#L18-L22

https://github.com/joomlatools/joomlatools-framework-files/blob/feature/36-is-audio-video/template/helper/player.php#L18-L21

**Comment by ercanozkaya** [comment]
@rmdstudio I can't see where \ComFilesTemplateHelperPlayer::$_SUPPORTED_FORMATS is used in the code?

**Comment by rmdstudio** [comment]
@ercanozkaya I'm using it in FILEman https://github.com/joomlatools/fileman/blob/feature/312-av-player/code/site/components/com_fileman/views/file/tmpl/gallery.html.php#L13

**Comment by johanjanssens** [comment]
@rmdstudio Can you please create a PR for this too?

**Comment by rmdstudio** [comment]
@johanjanssens these methods are no longer being used anywhere. They were used in the FILEman photoswipe plyr experiment. Do we still want to keep them?

**Comment by johanjanssens** [comment]
@rmdstudio No, they are are no longer needed this issue can be closed and the branch removed. Can you handle that?
