### ISSUE TITLE
Allow disabling trees on app from URL

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework-files#38]

**Comment by amazeika** [comment]
@ercanozkaya Just double check this and please tell me if it's alright.

**Comment by ercanozkaya** [comment]
@amazeika can we use $state->config here so we don't need to introduce extra methods?

You can set `$state->config->tree->enabled = false` in the controller so it would just work out of the box with no view additions. Thoughts?

**Comment by amazeika** [comment]
@ercanozkaya I Using state crossed my mind but I thought that it would be wrong to use it as it really doesn't represent a data state (as in not used by him). 

However, if we establish a convention like you suggest ($state->config) so that we can use this in the view without additional methods, why not. Better yet, this makes me think that we could introduce view states in the FW? this is exactly what the tree query parameter is doing, it's modifying the view ... would that make sense? @johanjanssens?

**Comment by johanjanssens** [comment]
@amazeika @ercanozkaya Isn't that what template and view parameters are for? 

I'm not a 100% sure what you are trying to do? You want to be able to decide of the tree is shown through the url (not such a good idea), or through a controller config setting (better idea) ?

**Comment by amazeika** [comment]
@johanjanssens FILEman talks to com:files through a dispatcher behavior (routable). This behavior forwards the request to com:files to render UIs and handle files operations. The only proper way I'm aware of to tell files to do something is through the URL unless we extend com:files, which is not seomthing we are not doing in any of our extensions. Doing it in the bootstraper to change the config of the files controller is not a good idea.

In this particular case, I'm telling files not to render trees. This is a property in the JS application that takes care of rendering the whole thing.

**Comment by amazeika** [comment]
@johanjanssens Agreed on points 1 and 2.

Regarding the additional note, this is exactly what I've had in mind and why I've talked about view state. We do set the model state in the controller by pushing the request data to it. A similar mechanism could be interesting for views. For example you may also have permission awareness in the view parameters by pushing the result of canXXX permission methods to the parameters container in the view context.

On the other hand for my particular issue I can resolve this otherwise. I've just remember that I can add a JS config object on the wrapping layout so that I can initialize the JS files app without tree support. I've coded this last year when working with attachments.

Cheers.

**Comment by amazeika** [comment]
@ercanozkaya Solved here: https://github.com/joomlatools/fileman/commit/e221eb2ae15cb8784f8267dbf28866885f288774

Marking this as invalid.

@johanjanssens Should we continue the discussion on view states in a new ticket on FW space?

**Comment by johanjanssens** [comment]
@amazeika If it's solved it's solved. View states can be discussed if needed. Kodekit solves most of this already though.
