### ISSUE TITLE
Re-factor copy/move JS

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework-files#40]
The copy/move UI should work without assuming that a tree instance is set in the app.

**Comment by amazeika** [comment]
@ercanozkaya Can you please review this code dude? This works well on FILEman with and without tree enabled within the app. Should be tested on DOCman also.

Please let me know what you think.

**Comment by ercanozkaya** [comment]
@amazeika There is an extra unnecessary condition in files.copymove.js:33. If you remove that everything else seems good to go. 
I tested Docman and it seems to work well

**Comment by amazeika** [comment]
@ercanozkaya woops for the duplicated condition. Forgot to clean that up. Thanks for the review.
