### ISSUE TITLE
AV Player Google Analytics

### ISSUE THREAD

**Issue by rmdstudio** [joomlatools/joomlatools-framework-files#45]
Implement google analytics for the audio/video player.

**Comment by rmdstudio** [comment]
@johanjanssens @ercanozkaya here is a quick and simple implementation of Google analytics for the AV player. I am listening for the pause event and if the current time of the video is greater than 3 seconds, I consider the media Played. The 3 second convention is what Facebook, Instagram, and Twitter are using. YouTube waits for 30 seconds before the video is considered viewed. 

* Category is either DOCman or FILEman or whatever component that is using this player
* Action is `Play {media type}`. Media type is: video, audio, vimeo, youtube
* Label is `{#id} {Title}` 

I tried passing a 4th custom parameter called time which is the current time the player has been stopped. The value isn't showing up anywhere in google analytics. 

The javascript code is in the `com:files.player.default.html`and it is being included only once. I can however add a `played_tracker` to the `ComFilesTemplateHelperPlayer` and add the code there. 
This way we have the option of including or excluding the GA using a menu item parameter. 

I'm looking forward to your feedback please  

<img width="1151" alt="screen shot 2017-07-29 at 2 39 20 pm" src="https://user-images.githubusercontent.com/559971/28748409-0e709964-746c-11e7-851b-860135d7cb1e.png">

<img width="1128" alt="screen shot 2017-07-29 at 2 38 03 pm" src="https://user-images.githubusercontent.com/559971/28748410-0fe6fb1c-746c-11e7-9943-93e672e4bb68.png">

**Comment by johanjanssens** [comment]
@rmdstudio Looking good. @ercanozkaya Can you review this?

**Comment by ercanozkaya** [comment]
@rmdstudio Nice :) 
I tested and changed the implementation a little bit. Before it was sending the event multiple times if you play/pause again. I made it so that if the video is played three seconds in a row it's considered played. Also made the parameters same as the download tracking in docman. Can you please see if it still works well on your end? Then we can merge

**Comment by rmdstudio** [comment]
@ercanozkaya thank you. Tested the code and it seems to be working as expected

<img width="1123" alt="screen shot 2017-08-09 at 2 37 50 pm" src="https://user-images.githubusercontent.com/559971/29145085-6150b95a-7d10-11e7-8cf4-8ee880f754f1.png">

**Comment by rmdstudio** [comment]
@ercanozkaya I've tested this in DOCman on the https://github.com/joomlatools/docman/tree/feature/1140-av-analytics-g branch. I need to see if FILEman needs any changes in order to work with the analytics.

**Comment by ercanozkaya** [comment]
Cool, merging it then
