### ISSUE TITLE
Create folders recursively 

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework-files#58]
When uploading files, if the container folder path doesn't exists, chunkable is unable to create the temporary folder.

**Comment by amazeika** [comment]
@ercanozkaya On folder adapter we also issue a simple mkdir (non-recursive) while copying and moving files.

We better make these recursive right?

**Comment by ercanozkaya** [comment]
@amazeika Chunkable only creates the `.tmp` folder so this mkdir statement will work as long as container path exists. 

Since this seems to manifest itself when you change the container root path, doesn't it make sense to do this on container path change?

**Comment by amazeika** [comment]
@ercanozkaya Yes, FILEman and DOCman create the container folders when saving settings. TEXTman doesn't. Instead it expects that the container folder gets created the first time it gets used. I guess that to avoid any kind of errors, all folder creation operation on FILEman should be recursive? Any reason not to?

**Comment by amazeika** [comment]
Marked as invalid.
