### ISSUE TITLE
Create mimetypes table

### ISSUE THREAD

**Issue by rmdstudio** [joomlatools/joomlatools-framework-files#7]
Docman uses a docman_mimetypes table to gather an extension<->mimetype map. This is highly useful when serving downloads and can be made generic in com:files.

Todo
- [ ] Move database table structure from install.sql of DOCman and table data from mimetypes.sql into install.sql of com_files
- [ ] Move mimetypes model into com_files
- [ ] Add another adapter to query this table ComFilesMixinMimetype and add it to the default adapter list in _initialize

**Comment by rmdstudio** [comment]
@johanjanssens @ercanozkaya is this issue still relevant?

**Comment by ercanozkaya** [comment]
@rmdstudio It is. It would be nice to complete this before 3.0 stable. Could you create a ticket in Docman too and then implement the changes? Then I'll test
